### ISSUE TITLE
Tapping Sign-in button does nothing

### ISSUE THREAD

**Issue by burkybang** [crypticplank/flappybird#28] opened 2021-10-08 22:36 UTC
After updating to 4.0.5, I noticed I wasn't signed in anymore. Tapping on the Sign-in button isn't doing anything. Same result after restarting the app

https://user-images.githubusercontent.com/927886/136631647-2a32955f-9f40-449d-998e-2baf3dcaa65a.MOV

**Comment by BrandonPlank** [comment] 2021-10-09 01:03
Yeah, so this is a bug. To fix it, fully remove the app and reinstall.

**Comment by burkybang** [comment] 2021-10-09 01:29
Uninstalling/reinstalling worked. Thanks.

I've never been able to get the one from your Cydia repo to work. It always crashes at launch. I have to install the ipa via AppSync.

**Comment by shadoez** [comment] 2021-11-09 14:59
I’ve also experienced this, reinstalling did not work. I’ve tried wiping data in Apps Manager & clearing the app’s cache.

Also when I try to tap the Leaderboard button it just freezes. 

Installing deb file results in crash upon startup.

**Comment by BrandonPlank** [comment] 2021-11-09 15:03
The leaderboard issue is because the server is offline right not.

Check the official team twitter

@FlappyBirdRev

**Comment by BrandonPlank** [comment] 2021-11-09 15:04
And I would refrain Installing the app from my cydia repo until I figure out what's wrong.

**Comment by 1345abozR** [comment] 2022-05-23 10:27
- 

> 1678

- [ ]   #@**_2345

- Duplicate of [#_**[](url)]([url](

> url

))

**Comment by 1345abozR** [comment] 2022-05-23 10:28
>

**Comment by 1345abozR** [comment] 2022-05-23 10:29
# @shadoez 

- [ ] 

> 

> **__**

**Comment by 1345abozR** [comment] 2022-05-23 10:29
Gyhhr654>764

- [ ] 

- [ ] @ @crypticplank

**Comment by crypticplank** [comment] 2022-06-11 23:30
Should be fixed in theory, re-open if it is not.

**Closed by crypticplank** 2022-06-11 23:30 UTC
Labels: bug
